In [3]:
#1.Write a NumPy program to create a null vector of size 10 and update sixth value to 11

import numpy as np
x=np.zeros(10,dtype=int)
print("Null Vector:",x)
x[6]=11
print("After Updating:",x)

Null Vector: [0 0 0 0 0 0 0 0 0 0]
After Updating: [ 0  0  0  0  0  0 11  0  0  0]


In [22]:
#2.Write a NumPy program to convert an array to a float type (5th and 2nd are the same)

a=[1,2,3,4]
b=np.array(a)
print("Original Array ",b)
x=np.asfarray(b)
print("After convertion ",x)

Original Array  [1 2 3 4]
After convertion  [1. 2. 3. 4.]


In [23]:
#3. Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10

a=np.arange(2,11)
a.reshape(3,3)


array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [52]:
#4. Write a NumPy program to convert a list of numeric value into a one-dimensional NumPy array

list1=[1,2,3,4,5,6,7,8,9,10]
list2=[22.1,45.3,23.1]
print(np.array(list1))
print(np.array(list2))

[ 1  2  3  4  5  6  7  8  9 10]
[22.1 45.3 23.1]


In [30]:
#6. Write a NumPy program to create an empty and a full array

print("Empty Array")
a=np.empty([3,3])
print(a)
print("\nFull Array")
b=np.full([3,3],2)
print(b)

Empty Array
[[6.23042070e-307 4.67296746e-307 1.69121096e-306]
 [1.60219035e-306 1.89146896e-307 7.56571288e-307]
 [3.11525958e-307 1.24610723e-306 0.00000000e+000]]

Full Array
[[2 2 2]
 [2 2 2]
 [2 2 2]]


In [31]:
#7. Write a NumPy program to convert a list and tuple into arrays

a=[1,2,3,4,5]
print(np.array(a))
b=(1,2,3,4,5)
print(np.array(b))

[1 2 3 4 5]
[1 2 3 4 5]


In [37]:
#8. Write a NumPy program to find the real and imaginary parts of an array of complex numbers

comp=[1+2j,5-77j,4-9j,90+7j]
a=np.array(comp)
for i in range(len(a)):
    print("The complex number is {}".format(a[i]))
    print("The real part is {}".format(a[i].real))
    print("The imaginary part is {}\n".format(a[i].imag))

The complex number is (1+2j)
The real part is 1.0
The imaginary part is 2.0

The complex number is (5-77j)
The real part is 5.0
The imaginary part is -77.0

The complex number is (4-9j)
The real part is 4.0
The imaginary part is -9.0

The complex number is (90+7j)
The real part is 90.0
The imaginary part is 7.0



In [38]:
#10.Write a Pandas program to select the specified columns and rows from a given DataFrame.
#Select 'name' and 'score' columns in rows 1, 3, 5, 6 from the following data frame.

exam_data  = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
        'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
        'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(exam_data , index=labels)
print("Select specific columns and rows:")
print(df.iloc[[1, 3, 5, 6], [0,1]])


Select specific columns and rows:
      name  score
b     Dima    9.0
d    James    NaN
f  Michael   20.0
g  Matthew   14.5


In [40]:
#11.Write a Pandas program to count the number of rows and columns of a DataFrame.
#Sample Python dictionary data and list labels:

print("Number rows ",df.shape[0])
print("Number of columns ",df.shape[1])

Number rows  10
Number of columns  4


In [41]:
#20. Write a Pandas program to count number of columns of a DataFrame.

print("Number of columns ",df.shape[1])

Number of columns  4


In [42]:
#21. Write a Pandas program to group by the first column and get second column as lists in rows

import pandas as pd
df = pd.DataFrame( {'col1':['C1','C1','C2','C2','C2','C3','C2'], 'col2':[1,2,3,3,4,6,5]})
print("Original DataFrame")
print(df)
df = df.groupby('col1')['col2'].apply(list)
print("\nGroup on the col1:")
print(df)


Original DataFrame
  col1  col2
0   C1     1
1   C1     2
2   C2     3
3   C2     3
4   C2     4
5   C3     6
6   C2     5

Group on the col1:
col1
C1          [1, 2]
C2    [3, 3, 4, 5]
C3             [6]
Name: col2, dtype: object


In [45]:
#22. Write a Pandas program to check whether a given column is present in a DataFrame or not.

import pandas as pd
d = {'col1': [1, 2, 3, 4, 7], 'col2': [4, 5, 6, 9, 5], 'col3': [7, 8, 12, 1, 11]}
df = pd.DataFrame(data=d)
print("Original DataFrame")
print(df)
a=input("Enter the column you want to search:")
if a in df.columns:
    print("Present")
else:
    print("Not present")

Original DataFrame
   col1  col2  col3
0     1     4     7
1     2     5     8
2     3     6    12
3     4     9     1
4     7     5    11
Enter the column you want to search:col2
Present


In [46]:
#23. Create two arrays of six elements. Write a NumPy program to count the number of
#instances of a value occurring in one array on the condition of another array.

x = np.array([10,-10,10,-10,-10,10])
y = np.array([.85,.45,.9,.8,.12,.6])
print("Original arrays:")
print(x)
print(y)
result=np.sum(((x==10)&(y>.5)))
print("\nNumber of instances of a value occurring in one array on the condition of another array:")
print(result)

Original arrays:
[ 10 -10  10 -10 -10  10]
[0.85 0.45 0.9  0.8  0.12 0.6 ]

Number of instances of a value occurring in one array on the condition of another array:
3


In [48]:
#24. Create a 2-dimensional array of size 2 x 3, composed of 4-byte integer elements. Write a
#NumPy program to find the number of occurrences of a sequence in the said array.

np_array = np.array([[1, 2, 3], [2, 1, 2]], np.int32)
print("Original Numpy array:")
print(np_array)
print("Type: ",type(np_array))
print("Sequence: 1,2",)
result = repr(np_array).count("1, 2")
print("Number of occurrences of the said sequence:",result)

Original Numpy array:
[[1 2 3]
 [2 1 2]]
Type:  <class 'numpy.ndarray'>
Sequence: 1,2
Number of occurrences of the said sequence: 2


In [49]:
#25. Write a NumPy program to merge three given NumPy arrays of same shape

arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
arr3 = np.array([9,10,11,12])
print("Original arrays:")
print(arr1)
print(arr2)
print(arr3)
result = np.concatenate((arr1, arr2, arr3))
print("\nAfter concatenate:")
print(result) 

Original arrays:
[1 2 3 4]
[5 6 7 8]
[ 9 10 11 12]

After concatenate:
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [53]:
#26. Write a NumPy program to combine last element with first element of two given ndarray with different shapes.

array1 =np.array(['PHP','JS','C++'])
array2 = np.array(['Python','C#', 'NumPy'])    
print("Original arrays:")          
print(array1)
print(array2)          
result  = np.r_[array1[:-1], [array1[-1]+array2[0]], array2[1:]]   
print("\nAfter Combining:")       
print(result)


Original arrays:
['PHP' 'JS' 'C++']
['Python' 'C#' 'NumPy']

After Combining:
['PHP' 'JS' 'C++Python' 'C#' 'NumPy']
